POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTgxNWI0ZTA5ZTRlN2E4NDA1YzI2ZiIsInVzZXJuYW1lIjoibWFydGluIiwiaWF0IjoxNzI5NzkxNzI0LCJleHAiOjE3Mjk3OTUzMjR9.FsUvAcT0vxNyu7DByz38TQMAgbczGWNal_xg5KqUrwM

{
    "title": "Using middleware to extract token",
    "author": "Martin C. Robert",
    "url": "https://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
    "likes": 10
}